apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-configmap
data:
  REDIS_ADDRESS: "auth-service-redis-clusterip-service:6379"
  REDIS_PASSWORD: ""
  REDIS_DB: "0"
  TOKEN_DURATION: "10m"
  GRPC_ADDRESS: "0.0.0.0:8080"
  ENVIRONMENT: "production"
  USER_SERVICE_ADDRESS: "user-service-cluster-ip-service:8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: stevensopi/auth-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: GRPC_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: auth-service-configmap
                  key: GRPC_ADDRESS
            - name: REDIS_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: auth-service-configmap
                  key: REDIS_ADDRESS
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: auth-service-configmap
                  key: REDIS_PASSWORD
            - name: REDIS_DB
              valueFrom:
                configMapKeyRef:
                  name: auth-service-configmap
                  key: REDIS_DB
            - name: TOKEN_DURATION
              valueFrom:
                configMapKeyRef:
                  name: auth-service-configmap
                  key: TOKEN_DURATION
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: auth-service-configmap
                  key: ENVIRONMENT
            - name: USER_SERVICE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: auth-service-configmap
                  key: USER_SERVICE_ADDRESS
            - name: SYMMETRIC_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-symmetric-key-secret
                  key: symmetric-key

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080