apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-redis
  template:
    metadata:
      labels:
        app: auth-service-redis
    spec:
      containers:
        - name: auth-service-redis
          image: redis
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: auth-service-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
