apiVersion: v1
type: ConfigMap
metadata:
  name: auth-service-configmap
data:
  REDIS_ADDRESS: auth-service-redis-clusterip:6379
  REDIS_PASSWORD: ""
  REDIS_DB: 0
  TOKEN_DURATION: 10m
  GRPC_ADDRESS: 0.0.0.0:8080
  ENVIRONMENT: production
  USER_SERVICE_ADDRESS: user-service-cluster-ip-service:8080

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLables:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    containers:
      - name: auth-service
        image: stevensopi/smart-investor-auth-service
        ports:
          - containerPort: 8080
        env:
          - name: GRPC_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: GRPC_ADDRESS
          - name: REDIS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: REDIS_PASSWORD
          - name: REDIS_DB
            valueFrom:
              configMapKeyRef:
                name: REDIS_DB
          - name: TOKEN_DURATION
            valueFrom:
              configMapKeyRef:
                name: TOKEN_DURATION
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: ENVIRONMENT
          - name: USER_SERVICE_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: USER_SERVICE_ADDRESS
          - name: SymmetricKey
            valueFrom:
              secretKeyRef:
                name: auth-service-symmetric-key-secret
                key: symmetric-key

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-cluster-ip-service
metadata:
  type: CluterIP
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  