apiVersion: apps/v1 
kind: Deployment
metadata:
  name: jaeger-deployment
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:latest
          ports:
            - containerPort: 4317  # OTLP gRPC
            - containerPort: 4318  # OTLP HTTP
            - containerPort: 16686 # UI
            - containerPort: 14268 # HTTP collector
            - containerPort: 14250 # gRPC collector
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"

---
apiVersion: v1
kind: Service
metadata: 
  name: jaeger-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: jaeger
    - name: http-query
      port: 16686
      targetPort: 16686
    - name: collector-http
      port: 14268
      targetPort: 14268
    - name: collector-grpc
      port: 14250
      targetPort: 14250
    - name: zipkin
      port: 9411
      targetPort: 9411
    - name: agent-udp-sampling
      port: 5778
      targetPort: 5778
    - name: agent-udp-compact
      port: 6831
      targetPort: 6831
      protocol: UDP
    - name: agent-udp-binary
      port: 6832
      targetPort: 6832
      protocol: UDP
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318