apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'auth-service'
        static_configs:
          - targets: ['auth-service-cluster-ip-service:8080']
      - job_name: 'user-service'
        static_configs:
          - targets: ['user-service-cluster-ip-service:8080']
      - job_name: 'user-service-db'
        static_configs:
          - targets: ['user-service-db-cluster-ip-service:9187']
      - job_name: 'auth-service-db'
        static_configs:
          - targets: ['auth-service-redis-cluster-ip-service:9121']
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
              readOnly: true
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config