apiVersion: apps/v1
kind: Deployment
metadata:
  name: symbol-manager-service-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symbol-manager-service-db
  template:
    metadata:
      labels:
        app: symbol-manager-service-db
    spec:
      containers:
        - name: symbol-manager-service-db
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: symbol-manager-service-db-secret
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: symbol-manager-service-db-secret
                  key: pass
            - name: POSTGRES_DB
              value: symbol-manager-db

        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter:v0.11.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9187
          env:
            - name: DATA_SOURCE_URI
              value: "postgresql://$(DATA_SOURCE_USER):$(DATA_SOURCE_PASS)@symbol-manager-service-db-cluster-ip-service:5432/symbol-manager-db?sslmode=disable"
            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: symbol-manager-service-db-secret
                  key: user
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: symbol-manager-service-db-secret
                  key: pass

---
apiVersion: v1
kind: Service
metadata:
  name: symbol-manager-service-db-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: symbol-manager-service-db
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: metrics
      protocol: TCP
      port: 9187
      targetPort: 9187
