apiVersion: v1
kind: ConfigMap
metadata:
  name: symbol-scraper-service-configmap
data:
  ENVIRONMENT: "production"
  SERVICE_NAME: "symbol-scraper"
  SCRAPE_INTERVAL: 200s
  SYMBOL_TOPIC: "scraping_topic"
  KAFKA_BROKER: my-kafka.kafka.svc.cluster.local:9092
  SCRAPE_ENDPOINT: host.docker.internal:9090
  SYMBOL_MANAGER_ADDR: symbol-manager-service-cluster-ip-service:8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: symbol-scraper-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symbol-scraper-service
  template:
    metadata:
      labels:
        app: symbol-scraper-service
    spec:
      containers:
        - name: symbol-scraper-service
          image: test_scraper_image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: symbol-scraper-service-configmap
                  key: ENVIRONMENT
            - name: ALPHA_VANTAGE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: symbol-scraper-service-secret
                  key: alpha_vantage_api_key
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: symbol-scraper-service-configmap
                  key: SERVICE_NAME
            - name: SCRAPE_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: symbol-scraper-service-configmap
                  key: SCRAPE_INTERVAL
            - name: SYMBOL_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: symbol-scraper-service-configmap
                  key: SYMBOL_TOPIC                 
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: symbol-scraper-service-configmap
                  key: KAFKA_BROKER
            - name: SCRAPE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: symbol-scraper-service-configmap
                  key: SCRAPE_ENDPOINT
            - name: SYMBOL_MANAGER_ADDR
              valueFrom:
                configMapKeyRef:
                  name: symbol-scraper-service-configmap
                  key: SYMBOL_MANAGER_ADDR
---
apiVersion: v1
kind: Service
metadata:
  name: symbol-scraper-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: symbol-scraper-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080