apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-db
  template:
    metadata:
      labels:
        app: user-service-db
    spec:
      containers:
        - name: user-service-db
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: user-service-db-secret
                  key: user-service-db-secret-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-service-db-secret
                  key: user-service-db-secret-password
            - name: POSTGRES_DB
              value: user-service-db

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-db-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: user-service-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432