apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
data:
  GRPC_SERVER_ADDRESS: 0.0.0.0:8080
  ENVIRONMENT: PRODUCTION
  EMAIL_VERIFICATION_CODE_LENGTH: 10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    containers:
      - name: user-service
        image: stevensopi/smart-investor-user-service
        ports:
          - containerPort: 8080
        env:
          - name: GRPC_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: user-service-configmap
                key: GRPC_SERVER_ADDRESS
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: user-service-configmap
                key: ENVIRONMENT
          - name: DB_CONNECTION
            valueFrom:
              secretKeyRef:
                name: user-service-db-connection-secret
                key: db-connection

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-cluster-ip-service
metadata:
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  
