replicaCount: 1

zookeper:
  replicaCount: 1
  auth:
    enabled: false

persistence:
  enabled: true
  size: 20Gi

resource:
  requests:
    memory: 2Gi
    cpu: 500m
  limits:
    memory: 4Gi
    cpu: 1